#!/bin/sh
#
# vyos policy agent for netplugd
#

dev="$1"
action="$2"

case "$action" in
in)
   run-parts -a $dev /etc/netplug/linkup.d
    ;;
out)
   run-parts -a $dev /etc/netplug/linkdown.d
    ;;

# probe loads and initialises the driver for the interface and brings the
# interface into the "up" state, so that it can generate netlink(7) events.
# This interferes with "admin down" for an interface. Thus, commented out. An
# "admin up" is treated as a "link up" and thus, "link up" action is executed.
# To execute "link down" action on "admin down", run appropriate script in
# /etc/netplug/linkdown.d
#probe)
#    ;;

*)
    exit 1
    ;;
esac
