#!/bin/sh
PREREQ=""
prereqs()
{
    echo "$PREREQ"
}
case $1 in
prereqs)
    prereqs
    exit 0
    ;;
esac
. /usr/share/initramfs-tools/hook-functions
# Begin real processing below this line

# include listed modules to initramfs but not load them without the necessity
manual_add_modules igb ixgbe ixgbevf i40e i40evf

# include modules from file (one per line) to initramfs but not load them without the necessity
# add_modules_from_file /tmp/modlist

# include listed modules to initramfs and load them during the boot
# force_load xxx
