#!/bin/sh
PREREQ=""
prereqs()
{
    echo "$PREREQ"
}
case $1 in
prereqs)
    prereqs
    exit 0
    ;;
esac
. /usr/share/initramfs-tools/hook-functions
# Begin real processing below this line

# include listed modules to initramfs but not load them without the necessity
manual_add_modules igb ixgbe ixgbevf i40e i40evf

# include modules from file (one per line) to initramfs but not load them without the necessity
# add_modules_from_file /tmp/modlist

# include listed modules to initramfs and load them during the boot
# force_load xxx

# executable to copy to initramfs, with library dependencies
copy_exec /usr/lib/x86_64-linux-gnu/libnss_dns.so.2

# missing fsck in initramfs
copy_exec /sbin/dosfsck
copy_exec /sbin/e2fsck
copy_exec /sbin/fsck
copy_exec /sbin/fsck.exfat
copy_exec /sbin/fsck.ext2
copy_exec /sbin/fsck.ext3
copy_exec /sbin/fsck.ext4
copy_exec /sbin/fsck.fat
copy_exec /sbin/fsck.msdos
copy_exec /sbin/fsck.vfat
copy_exec /sbin/logsave

# copy other files ("other" here is a file type, so do not delete this keyword)
copy_file other /etc/ssl/certs/ca-certificates.crt

