//! nftables script generation.
//!
//! qfappd owns a dedicated `inet qfappd` table with a forward-hook base chain
//! at `priority filter + 10` — deliberately NOT inside `vyos_filter`, which
//! VyOS regenerates (and would wipe) on every commit. Running after the VyOS
//! filter also means we only classify traffic the firewall already accepted,
//! and Suricata IPS (`action queue` rules inside vyos_filter) verdicts first.
//!
//! Three artifacts, all rendered from the same `ctmark::Layout` the daemon
//! uses, so kernel and userspace cannot disagree about bit positions:
//!  - [`render_table`]: full table definition (startup / reload-all)
//!  - [`render_bindings_reload`]: atomic flush+refill of the bindings chain
//!    (policy hot-reload; fast paths keep matching throughout)
//!  - [`render_teardown`]: delete the table (graceful shutdown → fail-open)
//!
//! Match values are validated at policy load (see `policy.rs`); rendering
//! still quotes and re-checks interface names as defense in depth because
//! this output is fed to `nft -f` as root.

use crate::config::FailMode;
use crate::ctmark::Layout;
use crate::policy::{CompiledBinding, L4Proto, MatchSpec, parse_cidr};

pub const TABLE: &str = "inet qfappd";
pub const BINDINGS_CHAIN: &str = "qf_bindings";

#[derive(Debug, Clone, Copy)]
pub struct QueueSpec {
    pub start: u16,
    pub count: u16,
    pub fail_mode: FailMode,
}

impl QueueSpec {
    fn stmt(&self) -> String {
        let mut flags: Vec<&str> = Vec::new();
        if self.count > 1 {
            flags.push("fanout");
        }
        if self.fail_mode == FailMode::Open {
            flags.push("bypass");
        }
        let to = if self.count > 1 {
            format!("{}-{}", self.start, self.start + self.count - 1)
        } else {
            self.start.to_string()
        };
        if flags.is_empty() {
            format!("queue to {to}")
        } else {
            format!("queue flags {} to {to}", flags.join(","))
        }
    }
}

/// Full table, idempotent (`declare; delete; define` so it works whether or
/// not a previous instance exists).
///
/// Verdict flow (no ctnetlink — everything is in-kernel and masked):
///  1. Fast paths match the CT mark and short-circuit classified flows.
///  2. New flows jump to qf_bindings, which sets the packet mark's ACTION_ID
///     and queues them to qfappd.
///  3. qfappd ACCEPTs each verdict packet with the packet mark encoding the
///     verdict (CLASSIFIED [+ BLOCK] + APP_ID, keeping the ACTION_ID bits).
///  4. On the reinjected packet, the persist rule copies the qfappd-owned mark
///     bits from the PACKET mark into the CT mark (masked — other subsystems'
///     low bits survive), and the block rule drops it if BLOCK is set. Both the
///     persistence and the drop of the triggering packet happen here, so a
///     blocked flow's very first classified packet is already dropped.
pub fn render_table(layout: &Layout, queues: QueueSpec, bindings: &[CompiledBinding]) -> String {
    let classified = layout.classified_mask();
    let block = layout.block_mask();
    let both = classified | block;
    let qfmask = layout.qf_mask();
    let mut out = String::new();
    out.push_str("#!/usr/sbin/nft -f\n# generated by qfappd — do not edit\n\n");
    out.push_str("table inet qfappd {}\ndelete table inet qfappd\n\n");
    out.push_str("table inet qfappd {\n");
    out.push_str("    chain forward {\n");
    out.push_str("        type filter hook forward priority filter + 10; policy accept;\n\n");
    out.push_str("        # fast paths: classified flows never reach userspace again\n");
    out.push_str(&format!(
        "        ct mark & {both:#010x} == {both:#010x} counter drop comment \"qfappd-block-fastpath\"\n"
    ));
    out.push_str(&format!(
        "        ct mark & {classified:#010x} == {classified:#010x} counter accept comment \"qfappd-allow-fastpath\"\n\n"
    ));
    out.push_str("        # only TCP/UDP flows are classified\n");
    out.push_str(&format!("        meta l4proto {{ tcp, udp }} jump {BINDINGS_CHAIN}\n\n"));
    out.push_str("        # persist qfappd's packet-mark verdict into the ct mark (masked),\n");
    out.push_str("        # then drop the flow if it was a block — both on this same packet.\n");
    out.push_str(&format!(
        "        meta mark & {classified:#010x} == {classified:#010x} ct mark set ct mark & {:#010x} | meta mark & {qfmask:#010x} counter comment \"qfappd-persist\"\n",
        !qfmask
    ));
    out.push_str(&format!(
        "        meta mark & {both:#010x} == {both:#010x} counter drop comment \"qfappd-block\"\n"
    ));
    out.push_str("    }\n\n");
    out.push_str(&format!("    chain {BINDINGS_CHAIN} {{\n"));
    for rule in binding_rules(layout, queues, bindings) {
        out.push_str("        ");
        out.push_str(&rule);
        out.push('\n');
    }
    out.push_str("    }\n}\n");
    out
}

/// Atomic bindings-chain refresh for policy hot-reload. Executed as a single
/// `nft -f` transaction: either the whole new rule set applies or none of it.
pub fn render_bindings_reload(
    layout: &Layout,
    queues: QueueSpec,
    bindings: &[CompiledBinding],
) -> String {
    let mut out = String::new();
    out.push_str(&format!("flush chain {TABLE} {BINDINGS_CHAIN}\n"));
    for rule in binding_rules(layout, queues, bindings) {
        out.push_str(&format!("add rule {TABLE} {BINDINGS_CHAIN} {rule}\n"));
    }
    out
}

/// Fail-open teardown for graceful shutdown; safe to run when the table is
/// already gone.
pub fn render_teardown() -> String {
    "table inet qfappd {}\ndelete table inet qfappd\n".to_string()
}

/// One binding expands to (matched families) × (l4 entries) rules.
fn binding_rules(layout: &Layout, queues: QueueSpec, bindings: &[CompiledBinding]) -> Vec<String> {
    let classified = layout.classified_mask();
    let mut rules = Vec::new();
    for b in bindings {
        let w = layout.encode_action(b.action_id);
        // The action id rides the PACKET mark (skb->mark), which NFQUEUE
        // delivers to qfappd and which it reads to pick the governing action.
        // Masked so any foreign skb->mark bits survive.
        let mark_set = format!(
            "meta mark set meta mark & {:#010x} | {:#010x}",
            !w.mask, w.value
        );
        // Guard so a reinjected, already-classified packet (qfappd set the
        // CLASSIFIED bit on its verdict) doesn't match another binding and get
        // re-queued; it falls through to the persist/drop rules instead.
        let guard = format!("meta mark & {classified:#010x} == 0x00000000 ");
        let queue = queues.stmt();
        let comment = format!("comment \"qfappd-b{}\"", b.binding_id);

        for family in matched_families(&b.match_spec) {
            let l4_variants: Vec<String> = if b.match_spec.l4.is_empty() {
                vec![String::new()]
            } else {
                b.match_spec
                    .l4
                    .iter()
                    .map(|l4| {
                        let proto = match l4.proto {
                            L4Proto::Tcp => "tcp",
                            L4Proto::Udp => "udp",
                        };
                        if l4.dports.is_empty() {
                            format!("meta l4proto {proto} ")
                        } else {
                            format!("{proto} dport {} ", set_of(l4.dports.iter().map(u16::to_string)))
                        }
                    })
                    .collect()
            };

            for l4 in &l4_variants {
                let mut rule = guard.clone();
                if let Some(m) = ifname_match("iifname", &b.match_spec.iifname) {
                    rule.push_str(&m);
                }
                if let Some(m) = ifname_match("oifname", &b.match_spec.oifname) {
                    rule.push_str(&m);
                }
                if let Some(f) = family {
                    if let Some(m) = addr_match(f, "saddr", &b.match_spec.saddr) {
                        rule.push_str(&m);
                    }
                    if let Some(m) = addr_match(f, "daddr", &b.match_spec.daddr) {
                        rule.push_str(&m);
                    }
                }
                rule.push_str(l4);
                rule.push_str(&format!("{mark_set} counter {queue} {comment}"));
                rules.push(rule);
            }
        }
    }
    rules
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Family {
    V4,
    V6,
}

impl Family {
    fn prefix(self) -> &'static str {
        match self {
            Family::V4 => "ip",
            Family::V6 => "ip6",
        }
    }
}

/// Which families a binding's address constraints allow. No addresses →
/// one family-agnostic rule (`None`). Addresses present → one rule per
/// family that has candidates in EVERY non-empty address field (a binding
/// whose saddr is v4-only can never match an IPv6 packet).
fn matched_families(m: &MatchSpec) -> Vec<Option<Family>> {
    if m.saddr.is_empty() && m.daddr.is_empty() {
        return vec![None];
    }
    let feasible = |f: Family| {
        let has = |addrs: &[String]| {
            addrs.is_empty()
                || addrs.iter().any(|a| {
                    parse_cidr(a).map(|(ip, _)| ip.is_ipv4() == (f == Family::V4)).unwrap_or(false)
                })
        };
        has(&m.saddr) && has(&m.daddr)
    };
    [Family::V4, Family::V6]
        .into_iter()
        .filter(|&f| feasible(f))
        .map(Some)
        .collect()
}

fn ifname_match(field: &str, names: &[String]) -> Option<String> {
    if names.is_empty() {
        return None;
    }
    // Defense in depth: policy validation already enforced this charset.
    let safe: Vec<String> = names
        .iter()
        .filter(|n| {
            !n.is_empty()
                && n.len() <= 15
                && n.chars().all(|c| c.is_ascii_alphanumeric() || matches!(c, '.' | '-' | '_' | '+' | '@' | ':'))
        })
        .map(|n| format!("\"{n}\""))
        .collect();
    if safe.is_empty() {
        return None;
    }
    Some(format!("{field} {} ", set_of(safe.into_iter())))
}

fn addr_match(family: Family, field: &str, addrs: &[String]) -> Option<String> {
    if addrs.is_empty() {
        return None;
    }
    let members: Vec<String> = addrs
        .iter()
        .filter_map(|a| parse_cidr(a).map(|(ip, plen)| (a, ip, plen)))
        .filter(|(_, ip, _)| ip.is_ipv4() == (family == Family::V4))
        .map(|(_, ip, plen)| {
            let max = if ip.is_ipv4() { 32 } else { 128 };
            if plen == max { ip.to_string() } else { format!("{ip}/{plen}") }
        })
        .collect();
    if members.is_empty() {
        return None;
    }
    Some(format!("{} {field} {} ", family.prefix(), set_of(members.into_iter())))
}

fn set_of(members: impl Iterator<Item = String>) -> String {
    let items: Vec<String> = members.collect();
    if items.len() == 1 {
        items.into_iter().next().unwrap()
    } else {
        format!("{{ {} }}", items.join(", "))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::policy::L4Match;

    fn binding(id: u32, action_id: u8, m: MatchSpec) -> CompiledBinding {
        CompiledBinding {
            binding_id: id,
            action_id,
            action_name: format!("A{action_id}"),
            description: String::new(),
            match_spec: m,
        }
    }

    fn queues() -> QueueSpec {
        QueueSpec { start: 100, count: 4, fail_mode: FailMode::Open }
    }

    #[test]
    fn table_has_fast_paths_and_hook() {
        let out = render_table(&Layout::default(), queues(), &[]);
        assert!(out.contains("type filter hook forward priority filter + 10; policy accept;"));
        assert!(out.contains("ct mark & 0xc0000000 == 0xc0000000 counter drop"));
        assert!(out.contains("ct mark & 0x80000000 == 0x80000000 counter accept"));
        assert!(out.contains("meta l4proto { tcp, udp } jump qf_bindings"));
        // persist packet-mark verdict into ct mark (masked), then block-drop
        assert!(out.contains(
            "meta mark & 0x80000000 == 0x80000000 ct mark set ct mark & 0x0000ffff | meta mark & 0xffff0000 counter"
        ));
        assert!(out.contains("meta mark & 0xc0000000 == 0xc0000000 counter drop comment \"qfappd-block\""));
        // idempotent preamble
        assert!(out.contains("table inet qfappd {}\ndelete table inet qfappd"));
    }

    #[test]
    fn binding_rule_masked_write_and_fanout() {
        let m = MatchSpec {
            iifname: vec!["eth1".into()],
            oifname: vec!["eth0".into()],
            ..Default::default()
        };
        let rules = binding_rules(&Layout::default(), queues(), &[binding(10, 1, m)]);
        assert_eq!(rules.len(), 1);
        assert_eq!(
            rules[0],
            "meta mark & 0x80000000 == 0x00000000 \
             iifname \"eth1\" oifname \"eth0\" \
             meta mark set meta mark & 0xfff8ffff | 0x00010000 \
             counter queue flags fanout,bypass to 100-103 comment \"qfappd-b10\""
        );
    }

    #[test]
    fn action_id_encoded_at_action_shift() {
        let rules = binding_rules(&Layout::default(), queues(), &[binding(1, 5, MatchSpec::default())]);
        assert!(rules[0].contains("| 0x00050000"), "{}", rules[0]);
    }

    #[test]
    fn fail_closed_drops_bypass_flag() {
        let q = QueueSpec { start: 100, count: 4, fail_mode: FailMode::Closed };
        let rules = binding_rules(&Layout::default(), q, &[binding(1, 1, MatchSpec::default())]);
        assert!(rules[0].contains("queue flags fanout to 100-103"));
        assert!(!rules[0].contains("bypass"));
    }

    #[test]
    fn single_queue_no_fanout() {
        let q = QueueSpec { start: 100, count: 1, fail_mode: FailMode::Open };
        let rules = binding_rules(&Layout::default(), q, &[binding(1, 1, MatchSpec::default())]);
        assert!(rules[0].contains("queue flags bypass to 100 "));
    }

    #[test]
    fn mixed_families_split_into_two_rules() {
        let m = MatchSpec {
            saddr: vec!["10.0.1.0/24".into(), "fd00::/64".into()],
            ..Default::default()
        };
        let rules = binding_rules(&Layout::default(), queues(), &[binding(1, 1, m)]);
        assert_eq!(rules.len(), 2);
        assert!(rules[0].contains("ip saddr 10.0.1.0/24"));
        assert!(rules[1].contains("ip6 saddr fd00::/64"));
    }

    #[test]
    fn v4_only_saddr_emits_no_v6_rule() {
        let m = MatchSpec { saddr: vec!["192.168.0.0/16".into()], ..Default::default() };
        let rules = binding_rules(&Layout::default(), queues(), &[binding(1, 1, m)]);
        assert_eq!(rules.len(), 1);
        assert!(rules[0].contains("ip saddr 192.168.0.0/16"));
    }

    #[test]
    fn contradictory_families_emit_nothing() {
        // saddr v4-only, daddr v6-only: impossible in either family
        let m = MatchSpec {
            saddr: vec!["10.0.0.0/8".into()],
            daddr: vec!["fd00::/8".into()],
            ..Default::default()
        };
        assert!(binding_rules(&Layout::default(), queues(), &[binding(1, 1, m)]).is_empty());
    }

    #[test]
    fn l4_variants_and_port_sets() {
        let m = MatchSpec {
            l4: vec![
                L4Match { proto: L4Proto::Tcp, dports: vec![443, 8443] },
                L4Match { proto: L4Proto::Udp, dports: vec![] },
            ],
            ..Default::default()
        };
        let rules = binding_rules(&Layout::default(), queues(), &[binding(1, 1, m)]);
        assert_eq!(rules.len(), 2);
        assert!(rules[0].contains("tcp dport { 443, 8443 }"));
        assert!(rules[1].contains("meta l4proto udp"));
    }

    #[test]
    fn multiple_ifaces_render_as_set() {
        let m = MatchSpec { iifname: vec!["eth1".into(), "eth2".into()], ..Default::default() };
        let rules = binding_rules(&Layout::default(), queues(), &[binding(1, 1, m)]);
        assert!(rules[0].contains("iifname { \"eth1\", \"eth2\" }"));
    }

    #[test]
    fn reload_is_flush_plus_adds() {
        let out = render_bindings_reload(
            &Layout::default(),
            queues(),
            &[binding(1, 1, MatchSpec::default()), binding(2, 2, MatchSpec::default())],
        );
        let lines: Vec<&str> = out.lines().collect();
        assert_eq!(lines[0], "flush chain inet qfappd qf_bindings");
        assert_eq!(lines.len(), 3);
        assert!(lines[1].starts_with("add rule inet qfappd qf_bindings "));
    }

    #[test]
    fn teardown_is_idempotent_delete() {
        assert_eq!(render_teardown(), "table inet qfappd {}\ndelete table inet qfappd\n");
    }

    #[test]
    fn hostile_ifname_is_dropped_even_if_validation_bypassed() {
        let m = MatchSpec { iifname: vec!["evil\" accept comment \"".into()], ..Default::default() };
        let rules = binding_rules(&Layout::default(), queues(), &[binding(1, 1, m)]);
        assert!(!rules[0].contains("evil"));
    }
}
