#!/bin/sh
# Copyright (C) 2016 VyOS maintainers and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 or later as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# File: build-flavour
# Purpose: Adds various data files to the build config
#          depending on the build flavour.


BUILD_TYPE=$(scripts/query-json build/build-config.json build_type)
BUILD_ARCH=$(scripts/query-json build/build-config.json architecture)

# Add debug tools if it's a development image
if [ $BUILD_TYPE = "development" ]; then
    cp data/package-lists/vyos-dev.list.chroot build/config/package-lists/
fi

# Install grub-pc if it's an x86 build
if [ $BUILD_ARCH  = 'amd64' -o $BUILD_ARCH = 'i386' ]; then
    cp data/package-lists/vyos-x86.list.chroot build/config/package-lists/
fi

# Install grub-efi-arm if it's an arm build
if [ $BUILD_ARCH  = 'armhf' -o $BUILD_ARCH = 'armel' -o $BUILD_ARCH = 'arm' ]; then
    cp data/package-lists/vyos-arm.list.chroot build/config/package-lists/
fi
