#!/usr/bin/env python3
#
# Copyright (C) 2015 VyOS maintainers and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 or later as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# File: check-config
# Purpose:
#   Checks if the build config file (build/build-config.json) exists.
#   This is to prevent accidental execution of plumbing make targets
#   from going too far and failing with confusing errors.


import sys
import json

import defaults


print("Checking build configuration")

try:
    with open(defaults.BUILD_CONFIG, 'r') as f:
        build_config = json.load(f)
except:
    print("Build config does not exist or is not a valid JSON file")
    print("Please run the ./configure script and try again")
    sys.exit(1)
