#!/usr/bin/env python

import sys
import os

import defaults


print("Checking build configuration")

if not os.path.exists(defaults.BUILD_CONFIG):
    print("Build config does not exist")
    print("Please run the ./configure script and try again")
    sys.exit(1)
