#!/usr/bin/env python3
#
# Copyright (C) 2016 VyOS maintainers and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 or later as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# File: check-vm-build-env
# Purpose:
#   Checks if packages required for VM image build are installed.


import os
import sys

import util

deps = {
    'packages': [
      'jq',
      'qemu-system-x86',
      'qemu-utils'
    ],
   'binaries': ['packer']
}

print("Checking if packages required for VyOS image build are installed")

checker = util.DependencyChecker(deps)

missing = checker.get_missing_dependencies()
if not missing:
    print("All dependencies are installed")
    sys.exit(0)
else:
    checker.print_missing_deps()
    if 'packer' in missing['binaries']:
        print("Your system does not have Packer.")
        print("Please install Packer from https://www.packer.io/downloads.html.")
    sys.exit(1)

sys.exit(0)
