#!/bin/sh

BUILD_DIR=$(scripts/query-json build/build-config.json build_dir)
BUILD_ARCH=$(scripts/query-json build/build-config.json architecture)
VERSION=$(cat $BUILD_DIR/version)

ln -rnsf $BUILD_DIR/live-image-$BUILD_ARCH.hybrid.iso $BUILD_DIR/vyos-$VERSION-$BUILD_ARCH.iso 


