#!/bin/sh -e

SRC_DIR=packages
DST_DIR=build/config/packages.chroot

echo "Importing local debian packages from $SRC_DIR"

mkdir -p $DST_DIR
for file in $(find $SRC_DIR -maxdepth 1 -name '*.deb'); do
    if [ -f "$file" ]; then
        echo "Adding $(basename $file)"
        cp $file $DST_DIR
    fi
done
