#!/usr/bin/env python

import sys
import os
import json

import pystache

import defaults
import util

util.check_build_config()

lb_config_tmpl = """
lb config noauto \
        --architectures {{architecture}} \
        --bootappend-live "boot=live components hostname=vyos username=live" \
        --bootloader syslinux \
        --binary-images iso-hybrid \
        --debian-installer false \
        --distribution jessie \
        --iso-application "VyOS" \
        --iso-publisher "{{build_by}}" \
        --iso-volume "VyOS" \
        --debootstrap-options "--variant=minbase --exclude=isc-dhcp-client,isc-dhcp-common,ifupdown" \
        "${@}"
"""

with open(defaults.BUILD_CONFIG, 'r') as f:
     build_config = json.load(f)

lb_config_command = pystache.render(lb_config_tmpl, build_config)

print("Configuring live-build")
os.chdir(defaults.BUILD_DIR)

result = os.system(lb_config_command)
if result > 0:
    print("live-build config failed")
    sys.exit(1)
