#!/usr/bin/env python3
#
# Copyright (C) 2015 VyOS maintainers and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 or later as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# File: pbuilder-setup
# Purpose:
#   Bootstraps a Debian environment for use by pbuilder.


import sys
import os
import json
import distutils.dir_util

import pystache

import defaults
import util

util.check_build_config()

pbuilder_create_cmd_tmpl= """
    sudo pbuilder --create \
                  --configfile {{pbuilder_config}}
"""

with open(defaults.BUILD_CONFIG, 'r') as f:
     build_config = json.load(f)

pbuilder_create_command = pystache.render(pbuilder_create_cmd_tmpl, build_config)

print("Creating a pbuilder environment")
#os.chdir(defaults.BUILD_DIR)

distutils.dir_util.mkpath(defaults.PBUILDER_DIR)

result = os.system(pbuilder_create_command)
if result > 0:
    print("pbuilder environment bootstrap failed")
    sys.exit(1)
