#!/usr/bin/env python

import sys
import os
import json
import distutils.dir_util

import pystache

import defaults
import util

util.check_build_config()

pbuilder_create_cmd_tmpl= """
    sudo pbuilder --create \
                  --configfile {{pbuilder_config}}
"""

with open(defaults.BUILD_CONFIG, 'r') as f:
     build_config = json.load(f)

pbuilder_create_command = pystache.render(pbuilder_create_cmd_tmpl, build_config)

print("Creating a pbuilder environment")
#os.chdir(defaults.BUILD_DIR)

distutils.dir_util.mkpath(defaults.PBUILDER_DIR)

result = os.system(pbuilder_create_command)
if result > 0:
    print("pbuilder environment bootstrap failed")
    sys.exit(1)

