#!/usr/bin/env python
#
# Copyright (C) 2015 VyOS maintainers and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 or later as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# File: pbuilder-config
# Purpose:
#   Generates a pbuilderrc file for use by package build scripts.


import sys
import os
import json

import pystache

import defaults
import util

util.check_build_config()

pbuilder_config_tmpl = """

BASETGZ={{build_dir}}/base.tgz
BUILDPLACE={{build_dir}}/pbuilder/
MIRRORSITE={{pbuilder_debian_mirror}}
BUILDRESULT={{build_dir}}/pbuilder/result/

DISTRIBUTION={{distribution}}

ARCHITECTURE={{architecture}}

"""

with open(defaults.BUILD_CONFIG, 'r') as f:
     build_config = json.load(f)

pbuilder_config = pystache.render(pbuilder_config_tmpl, build_config)

print("Configuring pbuilder")

with open(defaults.PBUILDER_CONFIG, 'w+') as f:
    f.write(pbuilder_config)
