#!/usr/bin/env python

import sys
import os
import json

import pystache

import defaults
import util

util.check_build_config()

pbuilder_config_tmpl = """

BASETGZ={{build_dir}}/base.tgz
BUILDPLACE={{build_dir}}/pbuilder/
MIRRORSITE={{pbuilder_debian_mirror}}
BUILDRESULT={{build_dir}}/pbuilder/result/

DISTRIBUTION={{distribution}}

ARCHITECTURE={{architecture}}

"""

with open(defaults.BUILD_CONFIG, 'r') as f:
     build_config = json.load(f)

pbuilder_config = pystache.render(pbuilder_config_tmpl, build_config)

print("Configuring pbuilder")

with open(defaults.PBUILDER_CONFIG, 'w+') as f:
    f.write(pbuilder_config)
