#!/usr/bin/python
# Copyright (C) 2016 VyOS maintainers and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 or later as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# File: query-config
# Purpose: Extracts field values from the build config,
#          for use in languages that can't handle JSON easily,
#          (I'm looking at you, Bourne shell!)


import sys
import json

import defaults
import util

if len(sys.argv) < 2:
    print("Usage: {0} <config field name>".format(sys.argv[0]))
    sys.exit(1)

util.check_build_config()
with open(defaults.BUILD_CONFIG, 'r') as f:
     build_config = json.load(f)

print(build_config[sys.argv[1]])
