#!/bin/sh

HTTPS_BASE_URL="https://github.com/vyos"
SSH_BASE_URL="git@github.com:vyos"

REMOTE=`git config remote.origin.url`

# extract vyatta-foo.git
BASENAME=`echo $REMOTE | sed -re 's!.*/(.*)$!\1!'`
echo "Changing remote for $BASENAME"

# Print usage if no arguments given
if [ -z "$1" ]; then
    echo "Switches remote URL to SSH or HTTPS"
    echo "Use \"$0 ssh\" to switch to SSH"
    echo "Use \"$0 https\" to switch to HTTPS"
fi

case $1 in
    ssh)
        echo "New remote: $SSH_BASE_URL/$BASENAME"
        git config remote.origin.url $SSH_BASE_URL/$BASENAME
        ;;
    https)
        echo "New remote: $HTTPS_BASE_URL/$BASENAME"
        git config remote.origin.url $HTTPS_BASE_URL/$BASENAME
        ;;
    *)
        echo "Wrong option, use \"ssh\" or \"https\""
        ;;
esac




