name: "PR Conflicts checker"
on:
  pull_request_target:
    types: [synchronize]

jobs:
  Conflict_Check:
    name: 'Check PR status: conflicts and resolution'
    runs-on: ubuntu-latest
    steps:
      - name: check if PRs are dirty
        uses: eps1lon/actions-label-merge-conflict@v3
        with:
          dirtyLabel: "state: conflict"
          removeOnDirtyLabel: "state: conflict resolved"
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          commentOnDirty: "This pull request has conflicts, please resolve those before we can evaluate the pull request."
          commentOnClean: "Conflicts have been resolved. A maintainer will review the pull request shortly."
